### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by gareththegeek** [gareththegeek/rollagon#26]
Implement about page and site navigation
The about page should provide link to GH issues for feedback etc.

**Comment by sentinelgreg** [comment]
I propose that we use this side-bar navigation - it would only appear once the user has entered the session properly. 
<img width="584" alt="image" src="https://user-images.githubusercontent.com/6580237/167220010-73123da2-ba31-4c34-9173-53b489fbde9e.png">
 It allows switching between contests and notes. A secondary navigation could have secondary pages - like the ABOUT page.

**Comment by sentinelgreg** [comment]
- [ ] Write final copy
- [ ] Create a cute illustration (or use the helmet placeholder)
- [ ]
