### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by sentinelgreg** [gareththegeek/rollagon#48]
- [x] Gather font files
- [ ] Implement in a way that doesn't rely on client side font availability

**Comment by gareththegeek** [comment]
@sentinelgreg - I think if you navigate here (and you have an Adobe logon), you can find the font and click the little mark-up icon to get some html to link to the font resources: https://fonts.adobe.com/fonts/trajan

**Comment by sentinelgreg** [comment]
Awesome, I bundled both the Trajan and Calluna fonts in this bundle: 
<link rel="stylesheet" href="https://use.typekit.net/cwj7tkx.css"> 
<img width="573" alt="image" src="https://user-images.githubusercontent.com/6580237/169347210-ad7ca380-17e2-447c-b94d-a4eb77d2b08f.png">
