### ISSUE TITLE
Numbers are displayed using incorrect font variant

### ISSUE THREAD

**Issue by gareththegeek** [gareththegeek/rollagon#78]
Numbers are using `old-style-nums` rather than `lining-nums` as per design

![image](https://user-images.githubusercontent.com/6231841/173042980-dd18f065-b4b6-4f3a-aaca-819f08be4c3e.png)

**Comment by sentinelgreg** [comment]
The font variants are looking good for the new elements. I'm assuming you're waiting to update the fonts for elements like the dice pool builder once you've built it?
