### ISSUE TITLE
Purpose and potential of individual user roles 

### ISSUE THREAD

**Issue by sentinelgreg** [gareththegeek/rollagon#9]
I was just curious what the vision is for individual user roles (like joining as strife player vs. hero player) is?
I'm not challenging it - it's only that the app as-is is pretty straightforward.

However, I could certainly see how useful roles would be if we expand the app further down the line.

**Comment by sentinelgreg** [comment]
The alternative to this would be a single "view" for all users in the session, e.g. every user could create a contest or build a given player's dice pool. 

Also, the difficulty of building the role functionality is probably the main reason to not do it, and you've already done it, so it's kind of a moot point!

**Comment by gareththegeek** [comment]
I thought that separating the roles would simplify the UI by making it focused on the specific role the player has. The hero players then have fewer buttons on screen, since hero players are more numerous and usually less experienced, that seemed like a good move.
